from __future__ import annotations

import asyncio
import json
import logging
import uuid
from pathlib import Path
from typing import Any
from urllib.request import urlopen

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.responses import RedirectResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from callio.config.settings import Settings, get_settings, reload_settings_from_env
from callio.web import WEB_CLIENT_PATH
from callio.core.database import Database
from callio.core.memory import MemoryHub
from callio.orchestrator import Orchestrator
from callio.worker.tasks import TaskDispatcher

logger = logging.getLogger(__name__)

_ENV_FILE = Path(__file__).resolve().parents[2] / ".env"
_EXAMPLE_ENV_FILE = Path(__file__).resolve().parents[2] / ".env.example"
_SETTINGS_KEYS = {
    "CALLIO_LLM_PROVIDER",
    "CALLIO_LLM_MODEL",
    "CALLIO_LLM_API_KEY",
    "CALLIO_LLM_BASE_URL",
    "CALLIO_OLLAMA_BASE_URL",
    "CALLIO_STT_BACKEND",
    "CALLIO_TTS_BACKEND",
    "CALLIO_HOST",
    "CALLIO_PORT",
}


def _load_env_map(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    result: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip().strip('"').strip("'")
    return result


def _load_runtime_settings_map() -> dict[str, str]:
    merged = _load_env_map(_EXAMPLE_ENV_FILE)
    merged.update(_load_env_map(_ENV_FILE))
    return {key: merged.get(key, "") for key in sorted(_SETTINGS_KEYS)}


def _save_runtime_settings_map(payload: dict[str, str]) -> None:
    merged = _load_env_map(_ENV_FILE)
    for key in _SETTINGS_KEYS:
        value = str(payload.get(key, "")).strip()
        if value:
            merged[key] = value
        else:
            merged.pop(key, None)
    lines = ["# Callio configuration — generated by web settings wizard", ""]
    for key in sorted(merged):
        if merged[key]:
            lines.append(f"{key}={merged[key]}")
    _ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _settings_missing_keys(settings_map: dict[str, str]) -> list[str]:
    provider = (settings_map.get("CALLIO_LLM_PROVIDER", "ollama") or "ollama").strip().lower()
    missing: list[str] = []
    if not settings_map.get("CALLIO_LLM_MODEL", "").strip():
        missing.append("CALLIO_LLM_MODEL")

    if provider == "ollama":
        if not settings_map.get("CALLIO_OLLAMA_BASE_URL", "").strip():
            missing.append("CALLIO_OLLAMA_BASE_URL")
    elif provider == "openai_compatible":
        if not settings_map.get("CALLIO_LLM_BASE_URL", "").strip():
            missing.append("CALLIO_LLM_BASE_URL")
        if not settings_map.get("CALLIO_LLM_API_KEY", "").strip():
            missing.append("CALLIO_LLM_API_KEY")
    elif provider in {"openai", "anthropic", "gemini"}:
        if not settings_map.get("CALLIO_LLM_API_KEY", "").strip():
            missing.append("CALLIO_LLM_API_KEY")
    return missing


def _ollama_tags_url(base_url: str) -> str:
    normalized = (base_url or "http://localhost:11434/v1").strip().rstrip("/")
    if normalized.endswith("/v1"):
        normalized = normalized[:-3]
    return f"{normalized}/api/tags"


def _fetch_ollama_models(base_url: str) -> tuple[list[str], str | None]:
    url = _ollama_tags_url(base_url)
    try:
        with urlopen(url, timeout=2.5) as response:  # nosec B310 - user-configured local/service URL
            payload = json.loads(response.read().decode("utf-8"))
    except Exception as exc:
        return [], str(exc)
    models = payload.get("models", []) if isinstance(payload, dict) else []
    names = sorted({str(item.get("name", "")).strip() for item in models if isinstance(item, dict) and item.get("name")})
    return names, None


def _ollama_error_hint(base_url: str, error: str | None) -> str:
    if not error:
        return ""
    normalized = (base_url or "").strip().lower()
    if "localhost" in normalized or "127.0.0.1" in normalized:
        return (
            "This app is running inside a container or remote workspace. "
            "In that environment, localhost points to the container itself, not your local machine. "
            "If Ollama is running on your computer, use a host-reachable address or rely on browser-side local detection."
        )
    if "connection refused" in error.lower():
        return "The target address was reached, but nothing is listening on port 11434. Start Ollama or verify the port."
    if "timed out" in error.lower():
        return "The address did not respond in time. Check firewall rules, routing, or whether the host is reachable from this environment."
    return "Verify the base URL and confirm that the Ollama API is reachable from the current runtime environment."


class TodoItem(BaseModel):
    node_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str | None = None
    feature_name: str
    description: str
    difficulty_level: int = 1


class SessionItem(BaseModel):
    session_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    transcript: str = ""
    summary: str = ""


class TaskConfirmRequest(BaseModel):
    node_ids: list[str] = Field(default_factory=list)
    confirm_all: bool = False


class TaskCancelRequest(BaseModel):
    node_ids: list[str] = Field(default_factory=list)


class SettingsUpdateRequest(BaseModel):
    settings: dict[str, str] = Field(default_factory=dict)


class ConnectionManager:
    def __init__(self) -> None:
        self.active_connections: set[WebSocket] = set()
        self._lock = asyncio.Lock()

    async def connect(self, websocket: WebSocket) -> None:
        await websocket.accept()
        async with self._lock:
            self.active_connections.add(websocket)

    async def disconnect(self, websocket: WebSocket) -> None:
        async with self._lock:
            self.active_connections.discard(websocket)

    async def broadcast_status(self, message: dict[str, Any]) -> None:
        async with self._lock:
            connections = set(self.active_connections)
        stale_connections: list[WebSocket] = []
        for connection in connections:
            try:
                await connection.send_json(message)
            except Exception:
                stale_connections.append(connection)
        if stale_connections:
            async with self._lock:
                for connection in stale_connections:
                    self.active_connections.discard(connection)


def create_app(settings: Settings | None = None) -> FastAPI:
    settings = settings or get_settings()
    Path(settings.app_dir).mkdir(parents=True, exist_ok=True)
    Path(settings.static_dir).mkdir(parents=True, exist_ok=True)
    Path(settings.mobile_dir).mkdir(parents=True, exist_ok=True)
    Path(settings.shared_dir).mkdir(parents=True, exist_ok=True)

    database = Database(settings)
    memory_hub = MemoryHub(database, settings)
    manager = ConnectionManager()
    task_dispatcher = TaskDispatcher(database, memory_hub, manager, settings)
    orchestrator = Orchestrator(database, manager, task_dispatcher, settings)

    app = FastAPI(title=settings.app_title, version=settings.app_version)

    @app.get("/")
    async def root() -> RedirectResponse:
        return RedirectResponse(url=WEB_CLIENT_PATH)

    app.mount("/static", StaticFiles(directory=settings.static_dir), name="static")
    app.mount("/app/web", StaticFiles(directory=settings.static_dir), name="app-web")
    app.mount("/app/mobile", StaticFiles(directory=settings.mobile_dir), name="app-mobile")
    app.mount("/app/shared", StaticFiles(directory=settings.shared_dir), name="app-shared")
    app.state.settings = settings
    app.state.database = database
    app.state.memory_hub = memory_hub
    app.state.status_manager = manager
    app.state.task_dispatcher = task_dispatcher
    app.state.orchestrator = orchestrator

    @app.on_event("startup")
    async def startup() -> None:
        database.initialize()
        resumed = await task_dispatcher.resume_pending()
        if resumed:
            logger.info("Resumed %d queued task(s)", resumed)

    @app.get("/api/v1/health")
    async def health() -> dict[str, Any]:
        whisper_ready = False
        try:
            from callio.voice.whisper_loader import get_preload_error, is_whisper_ready

            whisper_ready = is_whisper_ready()
            whisper_error = get_preload_error()
        except Exception:
            whisper_error = None

        return {
            "status": "ok",
            "database": Path(settings.db_path).exists(),
            "voice_enabled": True,
            "whisper_ready": whisper_ready,
            "whisper_error": whisper_error,
            "queue_backend": task_dispatcher.backend_name,
            "active_tasks": database.count_running_tasks_global(),
            "queue_depth": database.count_queued_tasks("PENDING"),
        }

    @app.get("/api/v1/settings")
    async def get_runtime_settings() -> dict[str, Any]:
        settings_map = _load_runtime_settings_map()
        missing = _settings_missing_keys(settings_map)
        return {
            "settings": settings_map,
            "configured": not missing,
            "missing": missing,
        }

    @app.put("/api/v1/settings")
    async def update_runtime_settings(body: SettingsUpdateRequest) -> dict[str, Any]:
        payload = {
            key: str(value)
            for key, value in (body.settings or {}).items()
            if key in _SETTINGS_KEYS
        }
        _save_runtime_settings_map(payload)
        refreshed_settings = reload_settings_from_env()
        app.state.settings = refreshed_settings
        settings_map = _load_runtime_settings_map()
        missing = _settings_missing_keys(settings_map)
        return {
            "status": "saved",
            "settings": settings_map,
            "configured": not missing,
            "missing": missing,
            "restart_required": False,
        }

    @app.get("/api/v1/settings/ollama-models")
    async def list_ollama_models(base_url: str = "") -> dict[str, Any]:
        effective_base = (base_url or "http://localhost:11434/v1").strip()
        models, error = _fetch_ollama_models(effective_base)
        return {
            "base_url": effective_base,
            "models": models,
            "error": error,
            "hint": _ollama_error_hint(effective_base, error),
            "reachable": error is None,
        }

    @app.get("/api/v1/tasks")
    async def list_tasks() -> dict[str, Any]:
        return {"items": database.list_spec_nodes()}

    @app.get("/api/v1/sessions/{session_id}")
    async def get_session(session_id: str) -> dict[str, Any]:
        row = database.get_session(session_id)
        if not row:
            return {"session_id": session_id, "found": False, "session": None}
        return {"session_id": session_id, "found": True, "session": row}

    @app.get("/api/v1/sessions")
    async def list_sessions() -> dict[str, Any]:
        return {"items": database.list_sessions()}

    @app.delete("/api/v1/sessions")
    async def clear_sessions() -> dict[str, Any]:
        cleared = database.clear_all_sessions()
        memory_hub.clear_all_session_memory()
        await manager.broadcast_status({
            "event": "SESSIONS_CLEARED",
            "counts": cleared,
        })
        return {
            "status": "cleared",
            "counts": cleared,
        }

    @app.get("/api/v1/tasks/{node_id}/runs")
    async def get_task_runs(node_id: str) -> dict[str, Any]:
        node = database.get_spec_node(node_id)
        if not node:
            return {"node_id": node_id, "runs": [], "node": None}
        return {"node_id": node_id, "node": node, "runs": database.list_task_runs_for_node(node_id)}

    @app.post("/api/v1/tasks/{node_id}/cancel")
    async def cancel_running_task(node_id: str) -> dict[str, Any]:
        return await task_dispatcher.cancel_running(node_id)

    @app.get("/api/v1/sessions/{session_id}/tasks")
    async def list_session_tasks(session_id: str) -> dict[str, Any]:
        return {
            "session_id": session_id,
            "tasks": database.list_spec_nodes(session_id=session_id),
            "progress": orchestrator.progress.snapshot(session_id),
            "events": orchestrator.events.list_for_session(session_id, limit=30),
        }

    @app.post("/api/v1/sessions/{session_id}/tasks/confirm")
    async def confirm_session_tasks(session_id: str, body: TaskConfirmRequest) -> dict[str, Any]:
        return await orchestrator.coordinator.confirm(
            session_id, body.node_ids, confirm_all=body.confirm_all,
        )

    @app.post("/api/v1/sessions/{session_id}/tasks/cancel")
    async def cancel_session_tasks(session_id: str, body: TaskCancelRequest) -> dict[str, Any]:
        return await orchestrator.proposals.cancel(session_id, body.node_ids)

    @app.post("/api/v1/sessions")
    async def create_session(session: SessionItem) -> dict[str, str]:
        memory_hub.store_episode(session.session_id, session.title, session.transcript, session.summary)
        await manager.broadcast_status({
            "event": "SESSION_STORED",
            "session_id": session.session_id,
            "title": session.title,
        })
        return {"status": "stored", "session_id": session.session_id}

    @app.websocket("/ws/status")
    async def websocket_status(websocket: WebSocket) -> None:
        await manager.connect(websocket)
        await websocket.send_json({
            "event": "SNAPSHOT",
            "tasks": database.list_spec_nodes(),
            "sessions": database.list_sessions(),
        })
        try:
            while True:
                data = await websocket.receive_text()
                await websocket.send_json({"status": "heartbeat", "received": data})
        except WebSocketDisconnect:
            await manager.disconnect(websocket)

    @app.post("/api/v1/tasks/dispatch")
    async def dispatch_task(todo: TodoItem) -> dict[str, str]:
        database.upsert_spec_node(
            todo.node_id,
            todo.feature_name,
            todo.description,
            session_id=todo.session_id,
            difficulty_level=todo.difficulty_level,
            status="PENDING",
        )
        await manager.broadcast_status({
            "event": "TASK_DISPATCHED",
            "node_id": todo.node_id,
            "feature_name": todo.feature_name,
            "status": "PENDING",
        })
        await task_dispatcher.dispatch(todo.model_dump())
        return {"status": "dispatched", "node_id": todo.node_id}

    return app
